### ISSUE TITLE
unrelated raylb cmake for android+

### ISSUE THREAD

**Issue by jestarray** [rivten/meshrekt#1]
Sorry for contacting you here but you have no email or anything linked at all

https://www.reddit.com/r/Zig/comments/17l4fwt/is_it_possible_to_make_android_appsgames_with_zig/
Came across your reddit post, could you tell me how you got cmake working with raylib and android?

**Comment by rivten** [comment]
Hey ! I’ll drop you an email since you set yours in your github :)
